Added an event to process swaps on Feign Death
Rottenbeer/ItemRack pull request #121
Opened 2020-08-25 03:00 UTC by caccavale

Moving into phase 5 of classic, hunters are beginning to swap trinkets 2-3 times per fight.  Trinket swapping using FD has been felt slower in Itemrack than using a spammable macro.  After some testing using a Weakaura which attempts to swap trinkets every frame after FD has been cast, it seems like this is because trinkets can be swapped earlier than the events which Itemrack uses to trigger processing the swap queue.

Using the same Weakaura I figured out that trinkets can be swapped as soon as the UNIT_AURA update corresponding to Feign Death's buff has been fired (assuming FD isn't resisted).  This is my attempt at having itemrack register for and respond to that event for responsive FD trinket swapping.

I'm really not a LUA dev and I'm by no means certain that `ItemRack.ProcessCombatQueue()` was the correct thing to do here, but it seems to be working much more consistently now and swapping around .6-1s after FD is cast.

Please let me know if you would suggest any changes!

2020-09-04 16:24 UTC, Rottenbeer commented
Hi

I'm afraid you can't implement it like this, e.g. you don't take into concern that players can disable events in the config menu and we also ony register events in ItemRack:RegisterEvents at load time.
- Please register the event in RegisterEvent and also unregister it properly.
- You can add a event handler for UNIT_AURA in OnPlayerLogin
- Calling ProcessCombatQueue() should be fine

2020-09-07 14:00 UTC, Rottenbeer requested changes
I commented on the pull request, please have a look.

2020-11-19 09:52 UTC, pshurgal commented on ItemRack/ItemRack.lua
> +			local _, _, _, _, _, _, _, _, _, spell_id = UnitAura("player", i, "HELPFUL|PLAYER|CANCELABLE")
I think you can use `select` here
```lua
local spell_id = select(10, UnitAura("player", i, "HELPFUL|PLAYER|CANCELABLE"))
```

2024-09-26 16:54 UTC, Rottenbeer commented
Not relevant anymore I guess.

2024-09-26 16:54 UTC, closed without merging